name: Push to Replicate

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Cog
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.R8_TOKEN }}

      - name: Push model to Replicate
        run: cog push r8.im/primeinc/audio-super-resolution
        